### ISSUE TITLE
How can I get and change Tokens for authorization?

### ISSUE THREAD

**Issue by kyungtaek** [SzymonLisowiec/node-epicgames-fortnite-client#19]
Great works! And It's very useful! 

By the way, I have a question.
I guess it needs 2 types token, one is Launcher authorization token, another is Fortnite authorization token. And It's in the source code. Right?

1. If the tokens are blocked by Epic games, How can I change the token?  It seemed that I can't change it because it's const values. 

2. How can I get the tokens from an official client? I tried to capture it on Mac via Charles, I could get a client token, but I couldn't get Fortnite auth token. How did you get it?

Thanks for your works!
Have a good day.

**Comment by SzymonLisowiec** [comment]
Fortnite auth token is constant value uses to exchange client token.
I have got fortnite auth token when Fortnite allows use software (e.g. Fiddler) to capture traffic. Currently you can get token by decrypt game files.
