### ISSUE TITLE
getStatsBR return "false" for some users

### ISSUE THREAD

**Issue by fabriciols** [SzymonLisowiec/node-epicgames-fortnite-client#2]
I have some users that the function getStatsBR return nothing... is this some kind of privacy enable on this accounts? 

I'm using the code from the "Example" section.
This is the "request" log output.

https://gist.github.com/fabriciols/2da823c1579cbaea78bccd14af52d80b

Sites like "https://fortnitetracker.com" can get the profile without any problem.
The displayName = Lmileo

**Comment by SzymonLisowiec** [comment]
Looks like `Lmileo` have private profile. He must change this option:
![image](https://user-images.githubusercontent.com/16546063/52966915-c8ecdf80-33a8-11e9-9e66-80195a06f478.png)

**Comment by fabriciols** [comment]
You are right, thank you
