### ISSUE TITLE
Fortnite: Cannot join into the party. Reason: Incompatible build id.

### ISSUE THREAD

**Issue by D4vid1k** [SzymonLisowiec/node-epicgames-fortnite-client#23]
Fortnite: Cannot join into the party. Reason: Incompatible build id.

How i can fix? Thanks! :)

I tried to change build id to the 10.30 (8569414) but it doesn't work!
Please help me!

**Comment by D4vid1k** [comment]
I want the 10.30 partyBuildId

**Comment by D4vid1k** [comment]
pls

**Comment by D4vid1k** [comment]
I really need help

**Comment by SzymonLisowiec** [comment]
https://github.com/SzymonLisowiec/node-epicgames-fortnite-client#warning-about-maintenance
