### ISSUE TITLE
can i get epicgames worker?

### ISSUE THREAD

**Issue by ScufRoyaleYt** [SzymonLisowiec/node-epicgames-fortnite-client#30]

**Comment by SzymonLisowiec** [comment]
What do you mean?

**Comment by ScufRoyaleYt** [comment]
Can i be epicgames worker?

Kysune <notifications@github.com> schrieb am Mi., 22. Apr. 2020, 14:18:

**Comment by SzymonLisowiec** [comment]
This library and me isn't associated with EpicGames company.
