### ISSUE TITLE
Invalid captcha

### ISSUE THREAD

**Issue by ghost** [SzymonLisowiec/node-epicgames-fortnite-client#33]
(node:20220) UnhandledPromiseRejectionWarning: Error: Unknown auth error: errors.com.epicgames.accountportal.captcha_invalid
    at AccountAuth.login (C:\Users\easto\node_modules\epicgames-client\src\Account\Auth.js:55:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SzymonLisowiec** [comment]
https://epicgames-client.kysune.me/Client.html#login-options-exchangecode
